<?php

namespace AppBundle\Repository;

/**
 * CotizadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotizadorRepository extends \Doctrine\ORM\EntityRepository
{
}
